/**
 * .claude/skills/humanities/<slug>/SKILL.md 와
 * .claude/agents/{research,validation}/dream-*.md 를
 * lib/prompts/_compiled/<category>_<slug>.ts 로 변환한다.
 *
 * v1.0: 원문 임베드 (frontmatter 포함). 백틱·${} 만 escape.
 * 토큰 부담은 Claude 프롬프트 캐싱으로 흡수.
 *
 * 사용: pnpm compile-prompts
 * 자동: pnpm build 직전 (prebuild 훅)
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

const ROOT = process.cwd();
const OUT = join(ROOT, 'lib', 'prompts', '_compiled');

type SourceKind = 'skill_dir' | 'agent_flat';

interface Source {
  category: string;
  dir: string;
  kind: SourceKind;
  /** agent_flat 에서 어떤 파일을 포함할지 결정 */
  filter?: (name: string) => boolean;
}

const SOURCES: Source[] = [
  {
    category: 'skill_humanities',
    dir: '.claude/skills/humanities',
    kind: 'skill_dir',
  },
  {
    category: 'agent_research',
    dir: '.claude/agents/research',
    kind: 'agent_flat',
    filter: (n) => n.startsWith('dream-') && n.endsWith('.md'),
  },
  {
    category: 'agent_validation',
    dir: '.claude/agents/validation',
    kind: 'agent_flat',
    filter: (n) => n.startsWith('dream-') && n.endsWith('.md'),
  },
];

export function toConstName(category: string, slug: string): string {
  return `${category}_${slug}`
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/_+/g, '_')
    .toUpperCase();
}

export function escapeForTemplate(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function toFileName(category: string, slug: string): string {
  return `${category}_${slug.replace(/-/g, '_')}.ts`;
}

interface CompileResult {
  files: number;
  exports: string[];
}

export function compile(): CompileResult {
  if (!existsSync(OUT)) {
    mkdirSync(OUT, { recursive: true });
  }

  const exports: string[] = [];
  let count = 0;

  for (const src of SOURCES) {
    const absDir = join(ROOT, src.dir);
    if (!existsSync(absDir)) {
      console.warn(`⚠️  source dir 미존재: ${src.dir}`);
      continue;
    }

    if (src.kind === 'skill_dir') {
      const subdirs = readdirSync(absDir).filter((n) => statSync(join(absDir, n)).isDirectory());
      for (const slug of subdirs) {
        const skillPath = join(absDir, slug, 'SKILL.md');
        if (!existsSync(skillPath)) continue;
        const content = readFileSync(skillPath, 'utf-8');
        const constName = toConstName(src.category, slug);
        const fileName = toFileName(src.category, slug);
        const ts = `// Auto-generated by scripts/compile-prompts.ts — DO NOT EDIT
// Source: ${src.dir}/${slug}/SKILL.md

export const ${constName} = \`${escapeForTemplate(content)}\`;
`;
        writeFileSync(join(OUT, fileName), ts);
        exports.push(`export { ${constName} } from './${fileName.replace(/\.ts$/, '')}';`);
        count += 1;
        console.warn(`✓ ${fileName}`);
      }
    } else {
      const files = readdirSync(absDir).filter((n) => src.filter?.(n) ?? false);
      for (const f of files) {
        const filePath = join(absDir, f);
        const content = readFileSync(filePath, 'utf-8');
        const slug = basename(f, '.md');
        const constName = toConstName(src.category, slug);
        const fileName = toFileName(src.category, slug);
        const ts = `// Auto-generated by scripts/compile-prompts.ts — DO NOT EDIT
// Source: ${src.dir}/${f}

export const ${constName} = \`${escapeForTemplate(content)}\`;
`;
        writeFileSync(join(OUT, fileName), ts);
        exports.push(`export { ${constName} } from './${fileName.replace(/\.ts$/, '')}';`);
        count += 1;
        console.warn(`✓ ${fileName}`);
      }
    }
  }

  writeFileSync(
    join(OUT, 'index.ts'),
    `// Auto-generated — DO NOT EDIT\n${exports.sort().join('\n')}\n`,
  );

  console.warn(`\n✓ ${count}개 prompt 컴파일 완료 (lib/prompts/_compiled/)`);
  return { files: count, exports };
}

// CLI 실행
if (process.argv[1]?.includes('compile-prompts')) {
  compile();
}
